---
- name: Configure UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow specific ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ufw_allowed_ports }}"

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure fail2ban is running
  service:
    name: fail2ban
    state: started
    enabled: yes