---
- name: restart nginx
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    services:
      - nginx
    state: present
    recreate: "always"

- name: reload systemd
  systemd:
    daemon_reload: yes